name: EPCore
version: '${version}'
main: net.emeraldprison.epcore.EPCore
api-version: 1.19
depend: [ PlaceholderAPI, WorldGuard, Vault, ActionBarAPI ]
softdepend: [ PlugMan ]
authors: [ Wolfeiii ]
description: The core plugin for the prison server EmeraldPrison. Rewritten by Wolfeiii.
website: https://emeraldprison.net
