settings:
  private-messages:
    material:
      type: "PAPER"
      color: "BLUE"
      display-name: "Private Messages"
      description:
        - "&7Whether you want private messages enabled."
    options:
      commands:
        - "[console] eco give <player> 1000"
        - "[player] say Hello"
      message: true
      toggle-message: "DMs"
      confirmation: false
      defaultEnabled: true